os:
  - linux

language: php

php:
  - '7.3'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - php artisan migrate 
  
services:
  - mysql

script:
  - vendor/bin/phpunit --coverage-text
  - phpcs


notifications:
  slack: karaoke-app-pwsz:hcSjS2KK9LFeVxT69ODLCyTb

